import * as THREE from '/vendor/three.module.js';
import { MAP, UNIT_TYPES } from '../shared/data.mjs';

const BLUE=0x7dcce7, RED=0xf29b86;
export class Battlefield {
 constructor(element, labels, quality='medium') {
  this.element=element;this.labels=labels;this.labelCtx=labels.getContext('2d');this.units=new Map();this.selected=new Set();this.center={x:MAP.width/2,y:MAP.height/2};this.zoom=1;this.state=null;this.frame=0;this.lastFog=0;this.effects=[];this.seenEvents=new Set();this.quality=quality;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x223b3e);this.scene.fog=new THREE.FogExp2(0x506b65,0.00027);this.smokeMeshes=new Map();
  this.renderer=new THREE.WebGLRenderer({antialias:quality!=='low',powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='low'?1:quality==='medium'?1.5:2));this.renderer.setClearColor(0x223b3e);this.renderer.outputColorSpace=THREE.SRGBColorSpace;element.appendChild(this.renderer.domElement);
  this.camera=new THREE.OrthographicCamera(-800,800,500,-500,1,4000);this.ray=new THREE.Raycaster();this.ground=new THREE.Plane(new THREE.Vector3(0,1,0),0);this.scene.add(new THREE.HemisphereLight(0xe6eee5,0x324942,2.5));const sun=new THREE.DirectionalLight(0xfff1d2,3);sun.position.set(-300,800,250);this.scene.add(sun);
  this.materials=new Map();this.makeTerrain();this.batchTerrain();this.resize();this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(element);this.lastTime=performance.now();this.fpsFrames=0;this.fpsTime=performance.now();this.fps=0;this.animate=this.animate.bind(this);requestAnimationFrame(this.animate);
 }
 material(color){if(!this.materials.has(color))this.materials.set(color,new THREE.MeshStandardMaterial({color,roughness:.97}));return this.materials.get(color)}
 box(w,h,d,color,x=0,y=0,z=0,parent=this.scene){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),this.material(color));m.position.set(x,y+h/2,z);parent.add(m);return m}
 plane(w,d,color,x,z,y=.3){const m=new THREE.Mesh(new THREE.PlaneGeometry(w,d),this.material(color));m.rotation.x=-Math.PI/2;m.position.set(x,y,z);this.scene.add(m);return m}
 makeTerrain(){
  this.box(MAP.width+160,12,MAP.height+160,0x354c45,MAP.width/2,-15,MAP.height/2);this.plane(MAP.width,MAP.height,0x657459,MAP.width/2,MAP.height/2,0);
  let seed=41;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
  for(let i=0;i<150;i++){const x=random()*MAP.width,y=random()*MAP.height;this.plane(35+random()*90,20+random()*70,[0x6e7b5b,0x5e7256,0x727e60,0x697655][i%4],x,y,.05)}
  const trees=[];
  for(const t of MAP.terrain){const x=t.x+t.w/2,z=t.y+t.h/2;if(t.type==='road'){this.plane(t.w,t.h,0x8c8e7b,x,z,.26);continue}if(t.type==='water'){this.plane(t.w,t.h,0x416f77,x,z,.16);continue}if(t.type==='forest'){this.plane(t.w,t.h,0x3f5a48,x,z,.18);const count=Math.min(85,Math.floor(t.w*t.h/1300));for(let j=0;j<count;j++)trees.push([t.x+random()*t.w,t.y+random()*t.h,10+random()*17]);continue}if(t.type==='town'){this.plane(t.w,t.h,0x8c8a72,x,z,.15);for(let a=18;a<t.w-10;a+=45)for(let b=18;b<t.h-10;b+=52){let h=10+random()*14;this.box(22,h,24,0xa0a08a,t.x+a,0,t.y+b);const roof=new THREE.Mesh(new THREE.ConeGeometry(20,8,4),this.material(0x626e6a));roof.rotation.y=Math.PI/4;roof.position.set(t.x+a,h+4,t.y+b);this.scene.add(roof)}}
  }
  const foliage=new THREE.InstancedMesh(new THREE.ConeGeometry(11,28,6),this.material(0x294f41),trees.length);const trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(1.6,2,10,5),this.material(0x655a40),trees.length);const matrix=new THREE.Matrix4();trees.forEach(([x,z,h],i)=>{matrix.compose(new THREE.Vector3(x,h/2+4,z),new THREE.Quaternion(),new THREE.Vector3(h/22,h/22,h/22));foliage.setMatrixAt(i,matrix);matrix.makeTranslation(x,5,z);trunks.setMatrixAt(i,matrix)});this.scene.add(foliage,trunks);
  this.sectorMeshes=new Map();for(const s of MAP.sectors){const ring=new THREE.Mesh(new THREE.RingGeometry(s.radius-2,s.radius+1.5,72),new THREE.MeshBasicMaterial({color:0xe0d9ac,transparent:true,opacity:.65,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(s.x,.7,s.y);this.scene.add(ring);this.sectorMeshes.set(s.id,ring);this.box(2,28,2,0xaab7a7,s.x,0,s.y);this.box(18,10,1,0xb6c4ad,s.x+9,17,s.y)}
  MAP.spawns.forEach((s,i)=>{const ring=new THREE.Mesh(new THREE.RingGeometry(183,186,80),new THREE.MeshBasicMaterial({color:i?RED:BLUE,transparent:true,opacity:.7,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(s.x,.8,s.y);this.scene.add(ring);for(let j=-1;j<=1;j++)this.box(24,9,18,i?0x8b7362:0x6b8380,s.x+j*32,0,s.y-70)});
  this.fogCanvas=document.createElement('canvas');this.fogCanvas.width=200;this.fogCanvas.height=125;this.fogCtx=this.fogCanvas.getContext('2d');this.explored=new Uint8Array(200*125);this.fogTexture=new THREE.CanvasTexture(this.fogCanvas);this.fogTexture.minFilter=THREE.LinearFilter;const mat=new THREE.MeshBasicMaterial({map:this.fogTexture,transparent:true,depthWrite:false,opacity:.85});this.fogMesh=new THREE.Mesh(new THREE.PlaneGeometry(MAP.width,MAP.height),mat);this.fogMesh.rotation.x=-Math.PI/2;this.fogMesh.position.set(MAP.width/2,38,MAP.height/2);this.fogMesh.renderOrder=2;this.scene.add(this.fogMesh);this.fogMesh.visible=false;
 }
 batchTerrain(){
  // Static meshes are merged by material to reduce draw calls on mobile GPUs.
  this.scene.updateMatrixWorld(true);const batches=new Map();
  for(const mesh of [...this.scene.children]){if(!mesh.isMesh||mesh.isInstancedMesh||!mesh.material.isMeshStandardMaterial)continue;const geometry=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry.clone();geometry.applyMatrix4(mesh.matrixWorld);const key=mesh.material.uuid;if(!batches.has(key))batches.set(key,{material:mesh.material,items:[]});batches.get(key).items.push(geometry);this.scene.remove(mesh);mesh.geometry.dispose()}
  for(const batch of batches.values()){const geometry=new THREE.BufferGeometry();for(const name of ['position','normal','uv']){const length=batch.items.reduce((n,g)=>n+g.attributes[name].array.length,0);const data=new Float32Array(length);let offset=0;for(const item of batch.items){data.set(item.attributes[name].array,offset);offset+=item.attributes[name].array.length}geometry.setAttribute(name,new THREE.BufferAttribute(data,name==='uv'?2:3))}geometry.computeBoundingSphere();this.scene.add(new THREE.Mesh(geometry,batch.material));for(const g of batch.items)g.dispose()}
 }
 makeUnit(type,team){
  const g=new THREE.Group(),color=team?0x8f7860:0x728f7a,dark=0x263a35,edge=team?RED:BLUE;const add=(w,h,d,c,x,y,z)=>this.box(w,h,d,c,x,y,z,g);
  const wheel=(x,z)=>{const w=new THREE.Mesh(new THREE.CylinderGeometry(3,3,3,8),this.material(dark));w.rotation.z=Math.PI/2;w.position.set(x,3,z);g.add(w)};
  if(type==='infantry'){for(const [x,z] of [[0,-6],[-5,3],[5,3]]){add(4,7,3,color,x,1,z);const head=new THREE.Mesh(new THREE.SphereGeometry(2.2,6,4),this.material(0x9fa18a));head.position.set(x,10,z);g.add(head);add(1,1,7,dark,x+2,6,z-3)}}
  else if(type==='helicopter'){add(10,8,23,color,0,0,0);add(3,3,24,color,0,3,19);add(5,5,10,0x38585e,0,1,-7);const rotor=add(46,.7,2,dark,0,11,0);rotor.name='rotor';add(2,.7,46,dark,0,11,0);add(21,1.5,2,dark,0,-2,5);add(2,1.5,20,dark,-10,-3,0);add(2,1.5,20,dark,10,-3,0)}
  else if(type==='jet'){add(8,5,38,color,0,0,0);add(38,1.5,10,color,0,1,5);add(17,1,5,color,0,3,17);add(1.5,9,7,color,0,3,16);const tip=new THREE.Mesh(new THREE.ConeGeometry(4,15,5),this.material(color));tip.rotation.x=-Math.PI/2;tip.position.set(0,2,-26);g.add(tip)}
  else{const w=type==='recon'?11:type==='tank'?20:17,d=type==='recon'?20:30;add(w,6,d,color,0,3,0);if(type==='tank'||type==='artillery'){add(5,6,d+3,dark,-w/2,0,0);add(5,6,d+3,dark,w/2,0,0)}else for(const z of [-9,7]){wheel(-w/2,z);wheel(w/2,z)}if(type==='supply'){add(16,12,20,0x849379,0,8,4);add(14,7,9,color,0,8,-11);add(8,.6,2,0xd0d5b0,0,21,4);add(2,.6,8,0xd0d5b0,0,21,4)}else if(type==='aa'){add(12,4,12,color,0,9,0);for(const x of [-4,4])add(2,2,20,dark,x,15,-6)}else if(type==='tank'||type==='artillery'){add(12,5,13,color,0,9,0);add(2.5,2.5,type==='artillery'?32:24,dark,0,12,-15)}else{add(w-4,5,10,color,0,9,-3);add(1.3,1.3,10,dark,0,14,-8)}}
  const ring=new THREE.Mesh(new THREE.RingGeometry(15,17,32),new THREE.MeshBasicMaterial({color:edge,side:THREE.DoubleSide,transparent:true,opacity:.85,depthTest:false}));ring.rotation.x=-Math.PI/2;ring.position.y=.5;ring.name='selection';ring.visible=false;g.add(ring);this.scene.add(g);return g;
 }
 setState(state,playerId){this.state=state;this.playerId=playerId;this.myTeam=state.players.find(p=>p.id===playerId)?.team??0;const ids=new Set();for(const u of state.units){if(u.loadedIn)continue;ids.add(u.id);let m=this.units.get(u.id);if(!m){m=this.makeUnit(u.type,u.team);m.position.set(u.x,UNIT_TYPES[u.type]?.domain==='air'?55:0,u.y);this.units.set(u.id,m)}m.userData.unit=u;m.getObjectByName('selection').visible=this.selected.has(u.id)}for(const [id,m]of this.units)if(!ids.has(id)){this.scene.remove(m);m.traverse(o=>{if(o.geometry)o.geometry.dispose()});this.units.delete(id)}for(const s of state.sectors)this.sectorMeshes.get(s.id)?.material.color.setHex(s.owner===0?BLUE:s.owner===1?RED:0xe0d9ac);this.fogMesh.visible=true;this.syncSmoke();
  for(const e of state.events??[]){if(this.seenEvents.has(e.id))continue;this.seenEvents.add(e.id);if(e.type==='shot'||e.type==='explosion'||e.type==='hit'){const mesh=new THREE.Mesh(new THREE.SphereGeometry(e.type==='explosion'?12:4,6,4),new THREE.MeshBasicMaterial({color:0xffd8a0,transparent:true,opacity:.9}));mesh.position.set(e.x,9,e.y);this.scene.add(mesh);this.effects.push({mesh,life:.3})}}if(this.seenEvents.size>400)this.seenEvents=new Set((state.events??[]).map(e=>e.id));
 }
 syncSmoke(){const ids=new Set();for(const s of this.state?.smokes??[]){ids.add(s.id);let mesh=this.smokeMeshes.get(s.id);if(!mesh){mesh=new THREE.Mesh(new THREE.SphereGeometry(1,10,6),new THREE.MeshBasicMaterial({color:0xd7d9cd,transparent:true,opacity:.45,depthWrite:false}));mesh.renderOrder=3;this.scene.add(mesh);this.smokeMeshes.set(s.id,mesh)}mesh.position.set(s.x,13,s.y);mesh.scale.set(s.radius,22,s.radius)}for(const[id,mesh]of this.smokeMeshes)if(!ids.has(id)){this.scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();this.smokeMeshes.delete(id)}}
 setSelected(ids){this.selected=new Set(ids);for(const [id,m]of this.units)m.getObjectByName('selection').visible=this.selected.has(id)}
 resize(){this.width=this.element.clientWidth;this.height=this.element.clientHeight;this.renderer.setSize(this.width,this.height,false);this.labels.width=this.width*devicePixelRatio;this.labels.height=this.height*devicePixelRatio;this.updateCamera()}
 updateCamera(){const h=980/this.zoom,w=h*this.width/this.height;this.camera.left=-w/2;this.camera.right=w/2;this.camera.top=h/2;this.camera.bottom=-h/2;this.camera.position.set(this.center.x,1000,this.center.y+720);this.camera.lookAt(this.center.x,0,this.center.y);this.camera.updateProjectionMatrix();this.camera.updateMatrixWorld()}
 worldAt(x,y){this.ray.setFromCamera(new THREE.Vector2(x/this.width*2-1,-y/this.height*2+1),this.camera);const p=new THREE.Vector3();return this.ray.ray.intersectPlane(this.ground,p)?{x:p.x,y:p.z}:null}
 screenAt(x,y,h=12){const p=new THREE.Vector3(x,h,y).project(this.camera);return {x:(p.x+1)*this.width/2,y:(1-p.y)*this.height/2}}
 pan(dx,dy){const a=this.worldAt(this.width/2,this.height/2),b=this.worldAt(this.width/2+dx,this.height/2+dy);if(a&&b)this.focus(this.center.x+a.x-b.x,this.center.y+a.y-b.y)}
 focus(x,y){this.center.x=Math.max(-80,Math.min(MAP.width+80,x));this.center.y=Math.max(-80,Math.min(MAP.height+80,y));this.updateCamera()}
 scale(factor,x=this.width/2,y=this.height/2){const before=this.worldAt(x,y);this.zoom=Math.max(.58,Math.min(3.6,this.zoom*factor));this.updateCamera();const after=this.worldAt(x,y);if(before&&after)this.focus(this.center.x+before.x-after.x,this.center.y+before.y-after.y)}
 pick(x,y,ownOnly=true){let best=null,min=30;for(const u of this.state?.units??[]){if(u.loadedIn||ownOnly&&u.ownerId!==this.playerId)continue;const p=this.screenAt(u.x,u.y,UNIT_TYPES[u.type]?.domain==='air'?62:12),d=Math.hypot(p.x-x,p.y-y);if(d<min){min=d;best=u}}return best}
 updateFog(){if(!this.state)return;const ctx=this.fogCtx,w=200,h=125;ctx.clearRect(0,0,w,h);const image=ctx.createImageData(w,h);const friends=this.state.units.filter(u=>u.team===this.myTeam&&!u.loadedIn);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x;let visible=false;for(const u of friends){const r=UNIT_TYPES[u.type]?.vision??180;if((u.x-x*8)**2+(u.y-y*8)**2<r*r){visible=true;break}}if(visible)this.explored[i]=1;image.data[i*4]=8;image.data[i*4+1]=18;image.data[i*4+2]=25;image.data[i*4+3]=visible?0:this.explored[i]?115:195}ctx.putImageData(image,0,0);this.fogTexture.needsUpdate=true}
 drawLabels(){const c=this.labelCtx;c.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);c.clearRect(0,0,this.width,this.height);if(!this.state)return;c.textAlign='center';for(const s of this.state.sectors){const p=this.screenAt(s.x,s.y,32);c.fillStyle='#10232be0';c.fillRect(p.x-37,p.y-25,74,22);c.fillStyle=s.owner===0?'#9edcff':s.owner===1?'#ffc0a6':'#e5e0bd';c.font='bold 11px Arial';c.fillText(s.name??s.id,p.x,p.y-10)}for(const u of this.state.units){if(u.loadedIn)continue;const p=this.screenAt(u.x,u.y,UNIT_TYPES[u.type]?.domain==='air'?72:20);if(p.x<0||p.x>this.width||p.y<0||p.y>this.height)continue;const sel=this.selected.has(u.id);c.fillStyle=u.team===0?'#98d8ed':'#f5a991';c.beginPath();c.moveTo(p.x,p.y-10);c.lineTo(p.x-4,p.y-16);c.lineTo(p.x+4,p.y-16);c.fill();if(sel||this.zoom>1.35){c.fillStyle='#0d1b22d9';c.fillRect(p.x-22,p.y-27,44,5);c.fillStyle=u.hp/(u.maxHp??UNIT_TYPES[u.type].hp)<.35?'#e19075':'#a9d59d';c.fillRect(p.x-22,p.y-27,44*Math.max(0,u.hp/(u.maxHp??UNIT_TYPES[u.type].hp)),4);if(sel){c.font='bold 10px Arial';c.fillStyle='#eff5ea';c.fillText(UNIT_TYPES[u.type].name,p.x,p.y-34)}}}}
 drawMinimap(canvas){if(!this.state)return;const c=canvas.getContext('2d'),sx=canvas.width/MAP.width,sy=canvas.height/MAP.height;c.fillStyle='#465b4c';c.fillRect(0,0,canvas.width,canvas.height);for(const t of MAP.terrain){c.fillStyle={forest:'#243f32',water:'#3e6970',town:'#8b8970',road:'#97937a'}[t.type]??'#5b7258';c.fillRect(t.x*sx,t.y*sy,t.w*sx,t.h*sy)}for(const s of this.state.sectors){c.strokeStyle=s.owner===0?'#91d9f4':s.owner===1?'#f3a38e':'#e0d9ac';c.beginPath();c.arc(s.x*sx,s.y*sy,s.radius*sx,0,Math.PI*2);c.stroke()}for(const u of this.state.units){if(u.loadedIn)continue;c.fillStyle=this.selected.has(u.id)?'#fff':u.team===0?'#8dd8f0':'#faa28a';c.fillRect(u.x*sx-2,u.y*sy-2,4,4)}const a=this.worldAt(0,0),b=this.worldAt(this.width,0),d=this.worldAt(this.width,this.height),e=this.worldAt(0,this.height);if(a&&b&&d&&e){c.strokeStyle='#e4ede7aa';c.beginPath();c.moveTo(a.x*sx,a.y*sy);for(const p of[b,d,e])c.lineTo(p.x*sx,p.y*sy);c.closePath();c.stroke()}}
 animate(now){requestAnimationFrame(this.animate);const dt=Math.min(.05,(now-this.lastTime)/1000);this.lastTime=now;for(const m of this.units.values()){const u=m.userData.unit;m.position.x+=(u.x-m.position.x)*Math.min(1,dt*16);m.position.z+=(u.y-m.position.z)*Math.min(1,dt*16);if(Number.isFinite(u.heading))m.rotation.y=-u.heading-Math.PI/2;const rotor=m.getObjectByName('rotor');if(rotor)rotor.rotation.y+=dt*35}for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.life-=dt;e.mesh.material.opacity=Math.max(0,e.life*3);e.mesh.scale.addScalar(dt*6);if(e.life<=0){this.scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();this.effects.splice(i,1)}}if(now-this.lastFog>700){this.updateFog();this.lastFog=now}this.renderer.render(this.scene,this.camera);this.drawLabels();this.fpsFrames++;if(now-this.fpsTime>1000){this.fps=Math.round(this.fpsFrames*1000/(now-this.fpsTime));this.fpsFrames=0;this.fpsTime=now}this.onFrame?.(dt)}
}


